apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mvn-pipeline-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/apac-3-grp-2-app-backend
    - name: image-repo
      value: quay.io/arief_hidayat/apac-3-grp-2-feedback-backend-service
    - name: app-name
      value: feedback-backend-service
    - name: mongo-connection
      value: "mongodb://mongo:27017"
  serviceAccountName: build-bot
  pipelineRef:
    name: mvn-pipeline
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi