apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  deployer
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - delete
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - configmaps
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
subjects:
  - kind: ServiceAccount
    name: build-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer