mongodb:
  host: "mongo"
  port: "27017"
  database: "cnb"

image:
  repository: quay.io/arief_hidayat/apac-3-grp-2-feedback-backend-service
  tag: 0.0.1
  pullSecret: arief-hidayat-quay-io-credentials-pull-secret
app:
  activeProfiles: dev
  name: feedback-backend-service
  imagePullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  # 'ingress', 'oc-route', or "none"
  expose: "oc-route"
  containerPort: "8080"



  