{{ if .Values.dev.kafka.enable }}
{{ if $.Values.common.clusterDomain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka
  {{ if $.Values.common.ingressClass }}
  annotations:
    kubernetes.io/ingress.class: {{ $.Values.common.ingressClass }}
  {{ end }}
spec:
  {{ if $.Values.common.ingressSecretName }}
  tls:
    - hosts:
        - {{ printf "kafka-%s.%s" $.Release.Name $.Values.common.clusterDomain }}
      secretName: {{$.Values.common.ingressSecretName}}
  {{ end }}
  rules:
    - host: {{ printf "kafka-%s.%s" $.Release.Name $.Values.common.clusterDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-cluster
                port:
                  number: 3030
    - host: {{ printf "kafka-%s-rest.%s" $.Release.Name $.Values.common.clusterDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-cluster
                port:
                  number: 8082
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    - name: "3030"
      port: 3030
      targetPort: 3030
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8082"
      port: 8082
      targetPort: 8082
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "9581"
      port: 9581
      targetPort: 9581
    - name: "9582"
      port: 9582
      targetPort: 9582
    - name: "9583"
      port: 9583
      targetPort: 9583
    - name: "9584"
      port: 9584
      targetPort: 9584
    - name: "9585"
      port: 9585
      targetPort: 9585
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: kafka-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-cluster
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-cluster
    spec:
      containers:
        - env:
            - name: ADV_HOST
              value: kafka-cluster.{{.Release.Namespace}}.svc.cluster.local
            - name: RUNTESTS
              value: "0"
          image: {{.Values.dev.kafka.image}}
          name: kafka-cluster
          ports:
            - containerPort: 2181
            - containerPort: 3030
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
            - containerPort: 9581
            - containerPort: 9582
            - containerPort: 9583
            - containerPort: 9584
            - containerPort: 9585
            - containerPort: 9092
          resources:
            {{ toYaml .Values.dev.kafka.resources | nindent 12 }}
      restartPolicy: Always

{{ end }}