apiVersion: v1
data:
{{- with .Values.common.secrets.weatherApi }}
  {{.apiKey.key}}: {{.apiKey.value | b64enc}}
{{- end }}
kind: Secret
metadata:
  name: weather-api
type: Opaque
---
apiVersion: v1
data:
{{- with .Values.common.secrets.mongodb }}
  {{.url.key}}: {{.url.value | b64enc}}
{{- end }}
kind: Secret
metadata:
  name: mongodb
type: Opaque
---
apiVersion: v1
data:
{{- with .Values.common.secrets.kafka }}
  {{.bootstrapServers.key}}: {{.bootstrapServers.value | b64enc}}
{{- end }}
kind: Secret
metadata:
  name: kafka
type: Opaque
---