---
apiVersion: v1
data:
{{- with .Values.common.secrets.mongodb }}
  {{.url.key}}: {{.url.value | b64enc}}
  {{.host.key}}: {{.host.value | b64enc}}
{{- end }}
kind: Secret
metadata:
  name: mongodb
type: Opaque
