---
apiVersion: v1
data:
  MONGODB_CONNECTIONSTRING: {{ printf "mongodb://%s:%s" .Values.mongodb.host .Values.mongodb.port | b64enc}}
  MONGODB_DATABASE: {{ .Values.mongodb.database | b64enc }}
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.mongodb.database | b64enc }}
  SPRING_DATA_MONGODB_HOST: {{ .Values.mongodb.host | b64enc }}
  SPRING_DATA_MONGODB_PORT: {{ .Values.mongodb.port | b64enc }}
kind: Secret
metadata:
  name: mongodb-{{.Release.Name}}
type: Opaque
